Repository rsksmart/lumino, pull requests merged in 2020-10, with the labels that each got.

#123 Fixing support for Lumino node to run without prompt
  raiden/ui/app.py
  raiden/ui/prompt.py
Labels: bug, cli

#124 RLP-814: fix test suite dependencies
  constraints.txt
Labels: bug, dependencies, test suite

#114 RLP-769: queue identifier obfuscation
  constraints.txt
  raiden/network/transport/matrix/transport.py
  raiden/raiden_event_handler.py
  raiden/raiden_service.py
  raiden/tests/integration/network/transport/test_matrix_transport.py
  transport/layer.py
  transport/message.py
  transport/node.py
Labels: builds on open pr, refactor, transport

#127 RLP-825: rename transport layer fields
  raiden/api/rest.py
  raiden/network/transport/matrix/layer.py
  raiden/raiden_event_handler.py
  raiden/raiden_service.py
  raiden/tests/integration/api/test_pythonapi.py
  raiden/tests/integration/long_running/test_integration_events.py
  raiden/tests/integration/long_running/test_settlement.py
  raiden/tests/integration/network/transport/test_matrix_transport.py
  raiden/tests/integration/test_pythonapi_base.py
  raiden/tests/integration/test_regression.py
  transport/layer.py
Labels: refactor, transport

#128 RLP-818 Ignoring processed messages for LC
  raiden/lightclient/handlers/light_client_message_handler.py
  raiden/raiden_event_handler.py
  raiden/storage/sqlite.py
Labels: enhancement, hub, light client messages, register secret, settlement light, unlock light

#129 Feature/rlp 824/set signed transaction for settlement light
  raiden/api/rest.py
  raiden/api/v1/encoding.py
  raiden/lightclient/handlers/light_client_message_handler.py
  raiden/raiden_event_handler.py
  raiden/storage/sqlite.py
Labels: enhancement, hub, light client messages, settlement light

#131 Fix/rlp 822/signed register secret
  raiden/api/rest.py
  raiden/api/v1/encoding.py
  raiden/api/v1/resources.py
  raiden/lightclient/handlers/light_client_message_handler.py
Labels: builds on open pr, register secret

#130 Fix/RLP-823/signed-unlock
  raiden/api/rest.py
  raiden/api/v1/encoding.py
  raiden/api/v1/resources.py
Labels: unlock light

#126 Feature/rlp 628/unlock light and register secret
  raiden/api/python.py
  raiden/api/rest.py
  raiden/api/v1/encoding.py
  raiden/api/v1/resources.py
  raiden/api/validations/light_client_authorization.py
  raiden/blockchain_events_handler.py
  raiden/lightclient/handlers/light_client_message_handler.py
  raiden/lightclient/lightclientmessages/light_client_non_closing_balance_proof.py
  raiden/lightclient/models/light_client_protocol_message.py
  raiden/messages.py
  raiden/network/proxies/secret_registry.py
  raiden/network/rpc/smartcontract_proxy.py
  raiden/raiden_event_handler.py
  raiden/storage/sqlite.py
  raiden/storage/utils.py
  raiden/transfer/channel.py
  raiden/transfer/events.py
  raiden/transfer/mediated_transfer/target.py
  raiden/transfer/secret_registry.py
  raiden/transfer/unlock.py
Labels: enhancement, register secret, unlock light

#136 bugfix/RLP-835/both_participants_are_lc
  raiden/transfer/token_network.py
Labels: bug

#138 RLP-832 Handle invite 2 lc's
  raiden/network/transport/matrix/client.py
  raiden/network/transport/matrix/utils.py
  raiden/tests/integration/long_running/test_settlement.py
  raiden/tests/integration/network/transport/test_matrix_transport.py
  raiden/tests/unit/test_matrix_presence.py
Labels: bug

#140 RLP-774: generalize LC onboarding
  raiden/api/python.py
  raiden/api/rest.py
  raiden/api/v1/encoding.py
  raiden/api/v1/resources.py
  raiden/network/transport/matrix/layer.py
  raiden/raiden_service.py
  transport/layer.py
  transport/node.py
Labels: builds on open pr, refactor, transport

#143 Bug fix/rlp 838/fixing tests
  raiden/api/python.py
  raiden/network/transport/matrix/transport.py
  raiden/tests/integration/fixtures/transport.py
  raiden/tests/integration/long_running/test_integration_events.py
  raiden/tests/integration/long_running/test_settlement.py
  raiden/tests/integration/network/transport/test_matrix_transport.py
  raiden/tests/integration/test_pythonapi_base.py
  raiden/tests/integration/test_send_queued_messages.py
  raiden/tests/integration/transfer/test_refundtransfer.py
  raiden/tests/unit/api/test_api.py
  raiden/tests/utils/mocks.py
  raiden/tests/utils/network.py
  raiden/tests/utils/protocol.py
  raiden/tests/utils/transfer.py
  raiden/transfer/node.py
  raiden/transfer/state.py
  raiden/transfer/views.py
Labels: bug, builds on open pr, test branch, test suite

#142 Bug fix/rlp 834/updating with develop
  constraints.txt
  raiden/api/objects.py
  raiden/api/python.py
  raiden/api/rest.py
  raiden/api/v1/encoding.py
  raiden/api/v1/resources.py
  raiden/api/validations/channel_validator.py
  raiden/api/validations/light_client_authorization.py
  raiden/blockchain_events_handler.py
  raiden/lightclient/handlers/light_client_message_handler.py
  raiden/lightclient/lightclientmessages/light_client_non_closing_balance_proof.py
  raiden/lightclient/models/light_client_protocol_message.py
  raiden/messages.py
  raiden/network/proxies/payment_channel.py
  raiden/network/proxies/secret_registry.py
  raiden/network/proxies/token_network.py
  raiden/network/rpc/smartcontract_proxy.py
  raiden/network/transport/matrix/client.py
  raiden/network/transport/matrix/transport.py
  raiden/network/transport/matrix/utils.py
  raiden/raiden_event_handler.py
  raiden/raiden_service.py
  raiden/storage/sqlite.py
  raiden/storage/utils.py
  raiden/tests/integration/fixtures/transport.py
  raiden/tests/integration/long_running/test_integration_events.py
  raiden/tests/integration/long_running/test_settlement.py
  raiden/tests/integration/network/transport/test_matrix_transport.py
  raiden/tests/integration/test_pythonapi_base.py
  raiden/tests/integration/test_send_queued_messages.py
  raiden/tests/integration/transfer/test_refundtransfer.py
  raiden/tests/unit/api/test_api.py
  raiden/tests/unit/test_matrix_presence.py
  raiden/tests/utils/mocks.py
  raiden/tests/utils/network.py
  raiden/tests/utils/protocol.py
  raiden/tests/utils/transfer.py
  raiden/transfer/channel.py
  raiden/transfer/events.py
  raiden/transfer/mediated_transfer/target.py
  raiden/transfer/node.py
  raiden/transfer/secret_registry.py
  raiden/transfer/state.py
  raiden/transfer/unlock.py
  raiden/transfer/views.py
  raiden/ui/app.py
  raiden/ui/prompt.py
Labels: builds on open pr

#146 RLP-755/fix-tests-wave-2
  raiden/network/transport/matrix/layer.py
Labels: bug

#110 RLP-750: transport generalization
  constraints.txt
  raiden/api/python.py
  raiden/api/rest.py
  raiden/api/v1/encoding.py
  raiden/api/v1/resources.py
  raiden/network/transport/__init__.py
  raiden/network/transport/matrix/__init__.py
  raiden/network/transport/matrix/client.py
  raiden/network/transport/matrix/layer.py
  raiden/network/transport/matrix/transport.py
  raiden/network/transport/matrix/utils.py
  raiden/raiden_event_handler.py
  raiden/raiden_service.py
  raiden/tests/integration/api/test_pythonapi.py
  raiden/tests/integration/fixtures/transport.py
  raiden/tests/integration/long_running/test_integration_events.py
  raiden/tests/integration/long_running/test_settlement.py
  raiden/tests/integration/network/transport/test_matrix_transport.py
  raiden/tests/integration/test_pythonapi_base.py
  raiden/tests/integration/test_raidenservice.py
  raiden/tests/integration/test_regression.py
  raiden/tests/integration/test_send_queued_messages.py
  raiden/tests/unit/test_matrix_presence.py
  raiden/tests/utils/network.py
  raiden/ui/app.py
  requirements.txt
  transport/__init__.py
  transport/config.py
  transport/layer.py
  transport/message.py
  transport/node.py
Labels: refactor, transport

#135 RLP-840: RIF Comms base
  raiden/network/transport/__init__.py
  raiden/network/transport/matrix/__init__.py
  raiden/network/transport/udp/__init__.py
  raiden/tests/integration/fixtures/transport.py
  raiden/tests/integration/long_running/test_stress.py
  raiden/tests/integration/network/transport/test_matrix_transport.py
  raiden/tests/integration/test_raidenservice.py
  raiden/tests/integration/test_recovery.py
  raiden/tests/integration/test_send_queued_messages.py
  raiden/tests/unit/test_logging.py
  raiden/tests/unit/test_matrix_presence.py
  raiden/tests/unit/test_matrix_transport_unit.py
  raiden/tests/unit/test_notifyingqueue.py
  raiden/tests/unit/test_startup.py
  raiden/tests/unit/test_udp_transport.py
  raiden/tests/utils/network.py
  raiden/ui/app.py
  raiden/ui/startup.py
  transport/config.py
  transport/matrix/__init__.py
  transport/matrix/client.py
  transport/matrix/layer.py
  transport/matrix/transport.py
  transport/matrix/utils.py
  transport/rif_comms/__init__.py
  transport/rif_comms/layer.py
  transport/rif_comms/node.py
  transport/udp/__init__.py
  transport/udp/healthcheck.py
  transport/udp/transport.py
  transport/udp/utils.py
Labels: refactor, transport

#147 bugfix/RLP-855/settlement-light
  raiden/api/rest.py
  raiden/api/v1/resources.py
Labels: bug, settlement light

#137 bugfix/RLP-836/cannot-receive-payments
  raiden/transfer/token_network.py
Labels: bug
