Repository rsksmart/lumino, pull requests merged in 2020-03, with the labels that each got.

#78 RLP-406 Each client has a different password for each homeserver
  raiden/api/python.py
  raiden/api/rest.py
  raiden/network/transport/matrix/__init__.py
  raiden/network/transport/matrix/transport.py
  raiden/network/transport/matrix/utils.py
  raiden/storage/restore.py
  raiden/storage/sqlite.py
  raiden/storage/utils.py
  raiden/tests/unit/test_lightclient_onboarding.py
  raiden/ui/app.py
Labels: hub

#80 RLP-406 Each client has a different password for each homeserver
  raiden/storage/utils.py
  raiden/ui/app.py
Labels: bug, hub

#81 RLP-574 Delete/Update old non closing balance proof
  raiden/network/proxies/payment_channel.py
  raiden/network/proxies/token_network.py
  raiden/raiden_event_handler.py
  raiden/storage/sqlite.py
  raiden/transfer/token_network.py
Labels: hub

#83 RLP-656/Added default value for signed_tx
  raiden/transfer/state_change.py
Labels: hub

#59 RLP-642/Fix-Refund-Transfers
  raiden/api/webui/static/endpointConfig.js
  raiden/message_handler.py
  raiden/messages.py
  raiden/raiden_event_handler.py
  raiden/tests/integration/test_regression.py
  raiden/tests/unit/test_sqlite.py
  raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py
  raiden/tests/utils/factories.py
  raiden/transfer/channel.py
  raiden/transfer/mediated_transfer/events.py
  raiden/transfer/mediated_transfer/initiator_manager.py
  raiden/transfer/mediated_transfer/mediator.py
  raiden/transfer/mediated_transfer/state_change.py
  raiden/transfer/node.py
Labels: bug, full node, request testing

#86 hotfix/RLP-692/onboarding-wrong-http-status
  raiden/api/rest.py
Labels: bug, hub

#85 feature/RLP-690/add-routing-mode
  raiden/app.py
  raiden/constants.py
  raiden/raiden_service.py
  raiden/ui/app.py
  raiden/ui/checks.py
  raiden/ui/cli.py
  raiden/ui/startup.py
Labels: full node, hub, mediation fees

#88 bugfix/RLP-693/Add-function-for-lockexpired
  raiden/transfer/mediated_transfer/target.py
Labels: bug, full node

#89 Bugfix/rlp 680/lc capacity
  raiden/api/python.py
  raiden/settings.py
  raiden/transfer/node.py
Labels: bug, hub
