Repository rsksmart/lumino, pull requests merged in 2020-02, with the labels that each got.

#69 Expired locked transfers are now stored in order that the LC can retr…
  raiden/lightclient/handlers/light_client_message_handler.py
  raiden/raiden_event_handler.py
  raiden/storage/sqlite.py
  raiden/transfer/mediated_transfer/target.py
Labels: hub

#68 When sending big amount values from LC it throws insert errors on SQLite
  raiden/lightclient/handlers/light_client_service.py
  raiden/storage/sqlite.py
  raiden/storage/utils.py
Labels: hub

#71 RLP-639/Contract without code
  raiden/blockchain_events_handler.py
  raiden/network/rpc/client.py
Labels: bug

#72 Light payment with not enough balance
  raiden/api/python.py
  raiden/lightclient/handlers/light_client_utils.py
Labels: bug, hub

#74 RLP-665 Apply PyLint to the lumino node
  raiden/api/python.py
  raiden/api/v1/resources.py
  raiden/api/validations/channel_validator.py
  raiden/lightclient/models/light_client_payment.py
  raiden/messages.py
  raiden/network/proxies/token_network.py
  raiden/raiden_event_handler.py
  raiden/transfer/channel.py
  raiden/transfer/mediated_transfer/events.py
  raiden/transfer/mediated_transfer/initiator_manager.py
  raiden/transfer/node.py
  raiden/transfer/state.py
  raiden/transfer/state_change.py
  raiden/transfer/token_network.py
  raiden/transfer/views.py
Labels: code cleanup, request testing

#75 Rlp 665/apply pylint to the lumino node 1
  raiden/api/python.py
  raiden/api/rest.py
  raiden/billing/invoices/invoice.py
  raiden/blockchain_events_handler.py
  raiden/connection_manager.py
  raiden/network/rpc/client.py
  raiden/network/transport/matrix/transport.py
  raiden/network/transport/matrix/utils.py
  raiden/raiden_event_handler.py
  raiden/raiden_service.py
  raiden/schedulers/alive_schedule.py
  raiden/schedulers/setup.py
  raiden/storage/sqlite.py
  raiden/transfer/channel.py
  raiden/transfer/mediated_transfer/events.py
  raiden/transfer/mediated_transfer/mediator.py
  raiden/transfer/node.py
  raiden/transfer/state.py
  raiden/transfer/views.py
  raiden/ui/console.py
  raiden/ui/explorer.py
  raiden/utils/rsk_gas_price_strategy/rsk_gas_price_strategy.py
  raiden/waiting.py
Labels: refactor

#76 RLP-671 PyLint Bugs
  .gitignore
  raiden/api/rest.py
  raiden/api/v1/encoding.py
  raiden/api/webui/static/endpointConfig.js
  raiden/connection_manager.py
  raiden/storage/restore.py
  raiden/tests/integration/test_recovery.py
  raiden/transfer/channel.py
  raiden/transfer/events.py
  raiden/transfer/mediated_transfer/events.py
  raiden/transfer/mediated_transfer/initiator.py
  raiden/transfer/mediated_transfer/mediator.py
  raiden/transfer/node.py
  raiden/transfer/views.py
  raiden/ui/console.py
  raiden/waiting.py
Labels: code cleanup, full node, hub, request testing
