Repository rsksmart/lumino, pull requests merged in 2021-03, with the labels that each got.

#216 RLP-1015: re-enable rif comms unsubscribe test
  raiden/tests/integration/network/transport/rif_comms/test_client.py
Labels: rif comms, test suite

#217 RLP-1028: invoice payment w/decimal amount
  raiden/api/v1/encoding.py
  raiden/utils/typing.py
Labels: bug

#219 RLP-1035 Adding missing dependencies on requirements.txt
  requirements-dev.txt
Labels: bug

#218 RLP-1031 Removing SQL print for payments on full node
  raiden/storage/sqlite.py
Labels: enhancement

#221 RLP-1037: invoice minimum amount
  raiden/billing/invoices/encoder/invoice_encoder.py
Labels: bug

#222 Bugfix/rlp 714/fix tests
  raiden/tests/integration/api/test_restapi.py
  raiden/tests/unit/test_logging.py
  raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py
Labels: test suite

#224 RLP-1043: channel details refresh fix
  raiden/api/rest.py
Labels: bug, full node, ui, web

#225 Fix issue with fails transactions in db
  raiden/api/python.py
  raiden/storage/sqlite.py
Labels: bug

#226 RLP-1048: update lumino-web
  .gitignore
  pip-wheel-metadata/raiden.dist-info/LICENSE
  pip-wheel-metadata/raiden.dist-info/METADATA
  pip-wheel-metadata/raiden.dist-info/entry_points.txt
  pip-wheel-metadata/raiden.dist-info/top_level.txt
  raiden/api/webui/asset-manifest.json
  raiden/api/webui/index.html
  raiden/api/webui/precache-manifest.07b1c4fdda8ac4df57d78be7811f9ac8.js
  raiden/api/webui/precache-manifest.d4fe5ba9b863bdceca0a0bb043a3069c.js
  raiden/api/webui/service-worker.js
  raiden/api/webui/static/css/2.96f4dcf5.chunk.css
  raiden/api/webui/static/css/2.96f4dcf5.chunk.css.map
  raiden/api/webui/static/css/2.eeb0d507.chunk.css
  raiden/api/webui/static/css/2.eeb0d507.chunk.css.map
  raiden/api/webui/static/css/main.3a32825c.chunk.css
  raiden/api/webui/static/css/main.3a32825c.chunk.css.map
  raiden/api/webui/static/css/main.96ab24dd.chunk.css
  raiden/api/webui/static/css/main.96ab24dd.chunk.css.map
  raiden/api/webui/static/endpointConfig.js
  raiden/api/webui/static/js/2.a559cd6d.chunk.js
  raiden/api/webui/static/js/2.ba736347.chunk.js
  raiden/api/webui/static/js/main.5d6ca77c.chunk.js
  raiden/api/webui/static/js/main.5d6ca77c.chunk.js.map
  raiden/api/webui/static/js/main.8abfc555.chunk.js
  raiden/api/webui/static/js/main.8abfc555.chunk.js.map
Labels: web

#230 RLP-1061 Fixing leave network to be a safe operation
  raiden/api/rest.py
Labels: bug

#231 Fix wrong filter in 'channel by partneraddress' view
  raiden/transfer/views.py
Labels: bug
