Repository rsksmart/lumino, pull requests merged in 2021-02, with the labels that each got.

#207 RLP-984 Fixing light payments without rbtc
  raiden/api/rest.py
Labels: bug, mediated light payments, p2p light payments

#208 RLP-1014: open channel crash (non-token SC address)
  raiden/api/validations/channel_validator.py
  raiden/exceptions.py
  raiden/network/blockchain_service.py
  raiden/tests/integration/network/transport/rif_comms/test_client.py
Labels: bug, open channel, open channel light, web

#212 RLP-995: update installation guides
  constraints.txt
  docs/0.1.0/install_macos.md
  docs/0.1.0/install_ubuntu.md
Labels: documentation

#213 RLP-1016 Fixing invoice payments
  raiden/api/python.py
  raiden/api/rest.py
Labels: bug
